name: Upload new release
on:
  release:
    types: [published]

jobs:
  upload_to_buckets:
    name: Upload to S3 buckets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aws_region:
          - 'us-east-1'
          - 'us-east-2'
          - 'us-west-1'
          - 'us-west-2'
          - 'eu-central-1'
          - 'eu-north-1'
          - 'eu-west-1'
          - 'eu-west-2'
          - 'eu-west-3'
          - 'sa-east-1'
          - 'ap-northeast-1'
          - 'ap-northeast-2'
          - 'ap-northeast-3'
          - 'ap-south-1'
          - 'ap-southeast-1'
          - 'ap-southeast-2'
          - 'ca-central-1'  
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Receive version clean
        id: version-receiver-without
        run: |
         version_without=$(echo ${github.event.release.tag_name:1})
         echo "version_without=${version_without}" >> "$GITHUB_ENV"
        shell: bash
      - name: create new version
        run: |
          cp ./sam-template.yaml ./sam-template-${{ matrix.aws_region }}.yaml
          sed -i "s/<<REGION>>/${{ matrix.aws_region }}/" "./sam-template-${{ matrix.aws_region }}.yaml"
        shell: bash
      - name: Upload to aws
        run: |
          sudo apt-get update
          sudo apt-get install awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set region ${{ matrix.aws_region }}
          aws s3 cp ./sam-template-${{ matrix.aws_region }}.yaml s3://logzio-aws-integrations-${{ matrix.aws_region }}/cloudwatch-logs-metrics/${{ env.version_without }}/sam-template.yaml --acl public-read
        shell: bash
      - name: Clean
        run: |
          rm ./sam-template-${{ matrix.aws_region }}.yaml